"""license_switch switch_uuid

Revision ID: 5824b1c6a0c6
Revises: 95d13495228a
Create Date: 2019-02-04 16:20:40.769697

"""
from alembic import op
import sqlalchemy as sa
import api_lic.migration_types


# revision identifiers, used by Alembic.
revision = '5824b1c6a0c6'
down_revision = '95d13495228a'
branch_labels = None
depends_on = None


def upgrade():
    #connection = op.get_bind()
    #connection.execute('delete from users')
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('license_switch', sa.Column('switch_uuid', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_license_switch_switch_uuid'), 'license_switch', ['switch_uuid'], unique=False)
    op.drop_index('ix_package_switch_switch_uuid', table_name='package_switch')
    op.drop_column('package_switch', 'switch_uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package_switch', sa.Column('switch_uuid', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.create_index('ix_package_switch_switch_uuid', 'package_switch', ['switch_uuid'], unique=False)
    op.drop_index(op.f('ix_license_switch_switch_uuid'), table_name='license_switch')
    op.drop_column('license_switch', 'switch_uuid')
    # ### end Alembic commands ###
