"""period ordered_amount

Revision ID: 68a956c4de09
Revises: 2d3470cd5603
Create Date: 2018-10-09 22:35:08.758651

"""
from alembic import op
import sqlalchemy as sa
import api_lic.migration_types


# revision identifiers, used by Alembic.
revision = '68a956c4de09'
down_revision = '2d3470cd5603'
branch_labels = None
depends_on = None


def upgrade():
    #connection = op.get_bind()
    #connection.execute('delete from users')
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('license_period', sa.Column('ordered_amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('license_period', 'ordered_amount')
    # ### end Alembic commands ###
