"""payment swith_uuid remove rel betwee switch_uuid inpackage

Revision ID: 98ce186d11f2
Revises: 6fa1546cba13
Create Date: 2018-12-07 01:50:53.954218

"""
from alembic import op
import sqlalchemy as sa
import api_lic.migration_types


# revision identifiers, used by Alembic.
revision = '98ce186d11f2'
down_revision = '6fa1546cba13'
branch_labels = None
depends_on = None


def upgrade():
    #connection = op.get_bind()
    #connection.execute('delete from users')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('package_switch_switch_uuid_fkey', 'package_switch', type_='foreignkey')
    op.add_column('payment', sa.Column('switch_uuid', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_payment_switch_uuid'), 'payment', ['switch_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_switch_uuid'), table_name='payment')
    op.drop_column('payment', 'switch_uuid')
    op.create_foreign_key('package_switch_switch_uuid_fkey', 'package_switch', 'switch', ['switch_uuid'], ['switch_uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###
