"""license_swict license_lrn del uniq

Revision ID: b07f61c2b5e5
Revises: 5824b1c6a0c6
Create Date: 2019-04-11 13:54:07.528669

"""
from alembic import op
import sqlalchemy as sa
import api_lic.migration_types


# revision identifiers, used by Alembic.
revision = 'b07f61c2b5e5'
down_revision = '5824b1c6a0c6'
branch_labels = None
depends_on = None


def upgrade():
    #connection = op.get_bind()
    #connection.execute('delete from users')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_license_lrn_package_lrn_uuid_user_uuid', 'license_lrn', type_='unique')
    op.drop_constraint('uq_license_switch_package_switch_uuid_user_uuid', 'license_switch', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_license_switch_package_switch_uuid_user_uuid', 'license_switch', ['package_switch_uuid', 'user_uuid'])
    op.create_unique_constraint('uq_license_lrn_package_lrn_uuid_user_uuid', 'license_lrn', ['package_lrn_uuid', 'user_uuid'])
    # ### end Alembic commands ###
