"""license enabled

Revision ID: cf0fe8ceaba4
Revises: 3d35a639b36b
Create Date: 2018-11-01 23:28:32.673005

"""
from alembic import op
import sqlalchemy as sa
import api_lic.migration_types


# revision identifiers, used by Alembic.
revision = 'cf0fe8ceaba4'
down_revision = '3d35a639b36b'
branch_labels = None
depends_on = None


def upgrade():
    #connection = op.get_bind()
    #connection.execute('delete from users')
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('license_lrn', sa.Column('is_enabled', sa.Boolean(), nullable=True))
    op.add_column('license_switch', sa.Column('is_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('license_switch', 'is_enabled')
    op.drop_column('license_lrn', 'is_enabled')
    # ### end Alembic commands ###
