"""switch

Revision ID: e19d1c7311c9
Revises: 79580b1c9691
Create Date: 2018-10-30 18:22:51.548051

"""
from alembic import op
import sqlalchemy as sa
import api_lic.migration_types


# revision identifiers, used by Alembic.
revision = 'e19d1c7311c9'
down_revision = '79580b1c9691'
branch_labels = None
depends_on = None


def upgrade():
    #connection = op.get_bind()
    #connection.execute('delete from users')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('switch',
    sa.Column('switch_uuid', sa.String(length=36), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('switch_ip', sa.String(length=16), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('current_port_count', sa.Integer(), nullable=True),
    sa.Column('minute_remaining', sa.Integer(), nullable=True),
    sa.Column('expired_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('switch_uuid')
    )
    op.add_column('package_switch', sa.Column('switch_uuid', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_package_switch_switch_uuid'), 'package_switch', ['switch_uuid'], unique=False)
    op.create_foreign_key(None, 'package_switch', 'switch', ['switch_uuid'], ['switch_uuid'], ondelete='CASCADE')
    op.drop_column('package_switch', 'switch_ip')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package_switch', sa.Column('switch_ip', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'package_switch', type_='foreignkey')
    op.drop_index(op.f('ix_package_switch_switch_uuid'), table_name='package_switch')
    op.drop_column('package_switch', 'switch_uuid')
    op.drop_table('switch')
    # ### end Alembic commands ###
