# coding: utf-8

"""
    LICENSE API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cli_lic
from cli_lic.rest import ApiException
from cli_lic.apis.admin_api import AdminApi


class TestAdminApi(unittest.TestCase):
    """ AdminApi unit test stubs """

    def setUp(self):
        self.api = cli_lic.apis.admin_api.AdminApi()

    def tearDown(self):
        pass

    def test_email_template_list_get(self):
        """
        Test case for email_template_list_get

        
        """
        pass

    def test_email_template_name_get(self):
        """
        Test case for email_template_name_get

        
        """
        pass

    def test_email_template_name_patch(self):
        """
        Test case for email_template_name_patch

        
        """
        pass

    def test_notification_notification_uuid_delete(self):
        """
        Test case for notification_notification_uuid_delete

        
        """
        pass

    def test_notification_notification_uuid_get(self):
        """
        Test case for notification_notification_uuid_get

        
        """
        pass

    def test_notification_notification_uuid_patch(self):
        """
        Test case for notification_notification_uuid_patch

        
        """
        pass

    def test_notification_post(self):
        """
        Test case for notification_post

        
        """
        pass

    def test_package_lrn_package_lrn_uuid_delete(self):
        """
        Test case for package_lrn_package_lrn_uuid_delete

        
        """
        pass

    def test_package_lrn_package_lrn_uuid_get(self):
        """
        Test case for package_lrn_package_lrn_uuid_get

        
        """
        pass

    def test_package_lrn_package_lrn_uuid_patch(self):
        """
        Test case for package_lrn_package_lrn_uuid_patch

        
        """
        pass

    def test_package_lrn_post(self):
        """
        Test case for package_lrn_post

        
        """
        pass

    def test_package_switch_package_switch_uuid_delete(self):
        """
        Test case for package_switch_package_switch_uuid_delete

        
        """
        pass

    def test_package_switch_package_switch_uuid_get(self):
        """
        Test case for package_switch_package_switch_uuid_get

        
        """
        pass

    def test_package_switch_package_switch_uuid_patch(self):
        """
        Test case for package_switch_package_switch_uuid_patch

        
        """
        pass

    def test_package_switch_post(self):
        """
        Test case for package_switch_post

        
        """
        pass

    def test_plan_plan_uuid_delete(self):
        """
        Test case for plan_plan_uuid_delete

        
        """
        pass

    def test_plan_plan_uuid_get(self):
        """
        Test case for plan_plan_uuid_get

        
        """
        pass

    def test_plan_plan_uuid_patch(self):
        """
        Test case for plan_plan_uuid_patch

        
        """
        pass

    def test_plan_post(self):
        """
        Test case for plan_post

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
