# coding: utf-8

"""
    LICENSE API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class LicenseModify(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'switch': 'LicenseSwitch',
        'lrn': 'LicenseLrn',
        'periods': 'list[LicensePeriod]',
        'rate_uuid': 'str'
    }

    attribute_map = {
        'switch': 'switch',
        'lrn': 'lrn',
        'periods': 'periods',
        'rate_uuid': 'rate_uuid'
    }

    def __init__(self, switch=None, lrn=None, periods=None, rate_uuid=None):
        """
        LicenseModify - a model defined in Swagger
        """

        self._switch = None
        self._lrn = None
        self._periods = None
        self._rate_uuid = None

        if switch is not None:
          self.switch = switch
        if lrn is not None:
          self.lrn = lrn
        if periods is not None:
          self.periods = periods
        if rate_uuid is not None:
          self.rate_uuid = rate_uuid

    @property
    def switch(self):
        """
        Gets the switch of this LicenseModify.

        :return: The switch of this LicenseModify.
        :rtype: LicenseSwitch
        """
        return self._switch

    @switch.setter
    def switch(self, switch):
        """
        Sets the switch of this LicenseModify.

        :param switch: The switch of this LicenseModify.
        :type: LicenseSwitch
        """

        self._switch = switch

    @property
    def lrn(self):
        """
        Gets the lrn of this LicenseModify.

        :return: The lrn of this LicenseModify.
        :rtype: LicenseLrn
        """
        return self._lrn

    @lrn.setter
    def lrn(self, lrn):
        """
        Sets the lrn of this LicenseModify.

        :param lrn: The lrn of this LicenseModify.
        :type: LicenseLrn
        """

        self._lrn = lrn

    @property
    def periods(self):
        """
        Gets the periods of this LicenseModify.

        :return: The periods of this LicenseModify.
        :rtype: list[LicensePeriod]
        """
        return self._periods

    @periods.setter
    def periods(self, periods):
        """
        Sets the periods of this LicenseModify.

        :param periods: The periods of this LicenseModify.
        :type: list[LicensePeriod]
        """

        self._periods = periods

    @property
    def rate_uuid(self):
        """
        Gets the rate_uuid of this LicenseModify.

        :return: The rate_uuid of this LicenseModify.
        :rtype: str
        """
        return self._rate_uuid

    @rate_uuid.setter
    def rate_uuid(self, rate_uuid):
        """
        Sets the rate_uuid of this LicenseModify.

        :param rate_uuid: The rate_uuid of this LicenseModify.
        :type: str
        """
        if rate_uuid is not None and len(rate_uuid) > 36:
            raise ValueError("Invalid value for `rate_uuid`, length must be less than or equal to `36`")

        self._rate_uuid = rate_uuid

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, LicenseModify):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
