# coding: utf-8

"""
    LICENSE API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ObjectCreatedCompositeOrStrPk(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'success': 'bool',
        'object_pk': 'str'
    }

    attribute_map = {
        'success': 'success',
        'object_pk': 'object_pk'
    }

    def __init__(self, success=True, object_pk=None):
        """
        ObjectCreatedCompositeOrStrPk - a model defined in Swagger
        """

        self._success = None
        self._object_pk = None

        if success is not None:
          self.success = success
        if object_pk is not None:
          self.object_pk = object_pk

    @property
    def success(self):
        """
        Gets the success of this ObjectCreatedCompositeOrStrPk.

        :return: The success of this ObjectCreatedCompositeOrStrPk.
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success):
        """
        Sets the success of this ObjectCreatedCompositeOrStrPk.

        :param success: The success of this ObjectCreatedCompositeOrStrPk.
        :type: bool
        """

        self._success = success

    @property
    def object_pk(self):
        """
        Gets the object_pk of this ObjectCreatedCompositeOrStrPk.

        :return: The object_pk of this ObjectCreatedCompositeOrStrPk.
        :rtype: str
        """
        return self._object_pk

    @object_pk.setter
    def object_pk(self, object_pk):
        """
        Sets the object_pk of this ObjectCreatedCompositeOrStrPk.

        :param object_pk: The object_pk of this ObjectCreatedCompositeOrStrPk.
        :type: str
        """

        self._object_pk = object_pk

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ObjectCreatedCompositeOrStrPk):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
